version: '4'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotels_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data

