{
 "title": "Micrometer Spring Throughput",
 "description": "Micrometer Http throughput dashboard ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status and SLA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{application=\"$application\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"hotel-svc:8081\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"hotel-svc:8081\"}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Mean response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"hotel-svc:8081\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"hotel-svc:8081\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\"}[1m])))"
    }
   ]
  }
 ]
}